spring.application.name=

server.port=8080

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud_name=
cloudinary.api_key=
cloudinary.api_secret=
